/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classification/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict Classification */
        post: operations["predict_classification_api_classification_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classification/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Classification Metrics */
        post: operations["classification_metrics_api_classification_metrics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/classification/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_api_classification_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/regression/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict Regression */
        post: operations["predict_regression_api_regression_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clustering/predict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Predict Clustering */
        post: operations["predict_clustering_api_clustering_predict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clustering/datasets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Datasets */
        get: operations["list_datasets_api_clustering_datasets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dim-reduction/reduce": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reduce Dimensions */
        post: operations["reduce_dimensions_api_dim_reduction_reduce_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dim-reduction/algorithms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Algorithms */
        get: operations["list_algorithms_api_dim_reduction_algorithms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ClassificationMetrics */
        ClassificationMetrics: {
            /** Accuracy */
            accuracy: number;
            /** Precision */
            precision: number;
            /** Recall */
            recall: number;
            /** F1 */
            f1: number;
            /** Confusion Matrix */
            confusion_matrix: number[][];
            /** Roc Curve */
            roc_curve: {
                [key: string]: unknown;
            };
            /** Log Loss */
            log_loss: number;
        };
        /** ClusteringRequest */
        ClusteringRequest: {
            /** Algorithm */
            algorithm: string;
            /** Dataset Name */
            dataset_name: string;
            /**
             * Hyperparameters
             * @default {}
             */
            hyperparameters: {
                [key: string]: unknown;
            };
            /**
             * Resolution
             * @default 100
             */
            resolution: number;
            /**
             * Noise
             * @default 0.5
             */
            noise: number;
            /**
             * N Samples
             * @default 300
             */
            n_samples: number;
        };
        /** ClusteringResponse */
        ClusteringResponse: {
            /** Label Grid */
            label_grid: number[][];
            points: components["schemas"]["DatasetSample"];
            /** Algorithm */
            algorithm: string;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Cache Hit */
            cache_hit: boolean;
            /** Grid Bounds */
            grid_bounds: {
                [key: string]: unknown;
            };
        };
        /** DatasetSample */
        DatasetSample: {
            /** X */
            X: number[][];
            /** Y */
            y: number[];
        };
        /** DimReductionRequest */
        DimReductionRequest: {
            /** Algorithm */
            algorithm: string;
            /** Dataset Name */
            dataset_name: string;
            /**
             * Hyperparameters
             * @default {}
             */
            hyperparameters: {
                [key: string]: unknown;
            };
            /**
             * N Components
             * @default 2
             */
            n_components: number;
            /**
             * Noise
             * @default 0.5
             */
            noise: number;
            /**
             * N Samples
             * @default 300
             */
            n_samples: number;
        };
        /** DimReductionResponse */
        DimReductionResponse: {
            /** Embedding */
            embedding: number[][];
            points: components["schemas"]["DatasetSample"];
            /** Algorithm */
            algorithm: string;
            /** Info */
            info: {
                [key: string]: unknown;
            };
            /** Cache Hit */
            cache_hit: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** MetricsRequest */
        MetricsRequest: {
            /** Algorithm */
            algorithm: string;
            /** Dataset Name */
            dataset_name: string;
            /**
             * Hyperparameters
             * @default {}
             */
            hyperparameters: {
                [key: string]: unknown;
            };
            /**
             * Noise
             * @default 0.5
             */
            noise: number;
            /**
             * N Samples
             * @default 300
             */
            n_samples: number;
        };
        /** PredictionRequest */
        PredictionRequest: {
            /** Algorithm */
            algorithm: string;
            /** Dataset Name */
            dataset_name: string;
            /**
             * Hyperparameters
             * @default {}
             */
            hyperparameters: {
                [key: string]: unknown;
            };
            /**
             * Resolution
             * @default 100
             */
            resolution: number;
            /**
             * Noise
             * @default 0.5
             */
            noise: number;
            /**
             * N Samples
             * @default 300
             */
            n_samples: number;
        };
        /** PredictionResponse */
        PredictionResponse: {
            /** Grid */
            grid: number[][];
            /** Contour Lines */
            contour_lines: number[][][];
            points: components["schemas"]["DatasetSample"];
            /** Algorithm */
            algorithm: string;
            /** Cache Hit */
            cache_hit: boolean;
            /** Grid Bounds */
            grid_bounds: {
                [key: string]: unknown;
            };
        };
        /** RegressionRequest */
        RegressionRequest: {
            /** Algorithm */
            algorithm: string;
            /** Dataset Name */
            dataset_name: string;
            /**
             * Hyperparameters
             * @default {}
             */
            hyperparameters: {
                [key: string]: unknown;
            };
            /**
             * Resolution
             * @default 100
             */
            resolution: number;
            /**
             * Noise
             * @default 0.5
             */
            noise: number;
            /**
             * N Samples
             * @default 300
             */
            n_samples: number;
        };
        /** RegressionResponse */
        RegressionResponse: {
            /** Grid */
            grid: number[][];
            /** Uncertainty Grid */
            uncertainty_grid?: number[][] | null;
            points: components["schemas"]["DatasetSample"];
            /** Algorithm */
            algorithm: string;
            /** Cache Hit */
            cache_hit: boolean;
            /** Grid Bounds */
            grid_bounds: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    predict_classification_api_classification_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PredictionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    classification_metrics_api_classification_metrics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MetricsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassificationMetrics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_api_classification_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    predict_regression_api_regression_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegressionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegressionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_clustering_api_clustering_predict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClusteringRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusteringResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_datasets_api_clustering_datasets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    reduce_dimensions_api_dim_reduction_reduce_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DimReductionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DimReductionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_algorithms_api_dim_reduction_algorithms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
